### ISSUE TITLE
Upgrading Ubuntu

### ISSUE THREAD

**Issue by KieranFitz3** [Ordissimo/scangearmp2#15]

**Comment by KieranFitz3** [comment]
Can you please advise on upgrading the scanner installation from 14.04  LTS to 18.04 LTS
Thanks

**Comment by Ordissimo** [comment]
Hi,
I keep the sources here, but the builds are available here: https://launchpad.net/~thierry-f/+archive/ubuntu/fork-michael-gruz

**Comment by KieranFitz3** [comment]
Upgraded to 16.04. Added the ppa to my system but my printer TS5050 is not
listed under cnijfilter or scangear2 am I missing something?
Kieran

**Comment by Ordissimo** [comment]
Le 2019-03-08 13:03, KieranFitz3 a écrit :
> Upgraded to 16.04. Added the ppa to my system but my printer TS5050 is
> not
> listed under cnijfilter or scangear2 am I missing something?
Hi Kieran,
The TS5050 uses the TS5000 Series driver.

**Comment by KieranFitz3** [comment]
Sorry can't find any reference to TS5000 series using Synaptic and
searching for scangearmp.    See screenshot.

Removed and reinstated the ppa

sudo add-apt-repository ppa:thierry-f/fork-michael-gruz
sudo apt-get update

At a loss as to what to do, pardon my ignorance.
Kieran

**Comment by Ordissimo** [comment]
Le 2019-03-08 16:50, KieranFitz3 a écrit :
> Sorry can't find any reference to TS5000 series using Synaptic and
> searching for scangearmp. See screenshot.
> 
> Removed and reinstated the ppa
> 
> sudo add-apt-repository ppa:thierry-f/fork-michael-gruz
> sudo apt-get update
> 
Okay.
For the printer you install cnijfiler2, it contains the TS5000 driver.
For the scanner, if you plug the printer into usb use the latest version 
of sane, otherwise, install scangearmp2 which contains the TS5000 
driver.

# For printer
sudp apt-get update, apt-get install cnijfilter2
# For scanner
sudp apt-get update, apt-get install scangearmp2

**Comment by KieranFitz3** [comment]
All working thanks, great work.
Kieran
