### ISSUE TITLE
debuild can't extract name and version

### ISSUE THREAD

**Issue by brentr** [Ordissimo/scangearmp2#22]
After I remove the format file, debuild grinds for a while, but ends without producing a .deb file
Lots of warnings like this:

dpkg-shlibdeps: warning: can't extract name and version from library name 'libcncpnet2.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libcncpnet2.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libcncpnet20.so'
dpkg-shlibdeps: warning: can't extract name and version from library name 'libcncpnet30.so'

It seems not to be finding the common lib files.

Any ideas?
Thanks in advance

**Comment by Ordissimo** [comment]
These are libraries provided by canon, debian has no infos on them. That's why you have warnings.
To solve this problem I rewrote part of the code by removing everything that belonged to Canon.
1 - You install the latest version of scangearmp2.
2 - You download the sources  [libmfp2-canon](https://github.com/Ordissimo/libmfp2-canon)
3 - You build the pakage and install it!

I don't know what your scanner is, but for the record, the driver provided here is very limited.
The latest version of sane supports all usb scanners and many network scanners.
A new backend has been added escl (http://www.sane-project.org/lists/sane-backends-cvs.html), dedicated to the network scanner at the moment.
You can find the list of supported devices here: https://support.apple.com/en-us/HT201311.
